version = "2026-08-13-v1"
effective_from = 20090101
buckets = [0.00, 0.01, 0.02, 0.03, 0.04]

[sw1_default]
"煤炭" = 0.00
"钢铁" = 0.00
"综合" = 0.00
"石油石化" = 0.01
"建筑材料" = 0.01
"建筑装饰" = 0.01
"交通运输" = 0.01
"纺织服饰" = 0.01
"公用事业" = 0.01
"农林牧渔" = 0.02
"商贸零售" = 0.02
"社会服务" = 0.02
"轻工制造" = 0.02
"家用电器" = 0.02
"食品饮料" = 0.02
"美容护理" = 0.02
"环保" = 0.02
"银行" = 0.02
"非银金融" = 0.02
"房地产" = 0.02
"医药生物" = 0.03
"传媒" = 0.03
"汽车" = 0.03
"机械设备" = 0.03
"基础化工" = 0.03
"有色金属" = 0.03
"电子" = 0.04
"计算机" = 0.04
"通信" = 0.04
"电力设备" = 0.04
"国防军工" = 0.04

[sw3_override]
